# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@2

      # Deploy
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          # Private Key secrets.DEPLOY_KEY就是刚才配置的密钥名
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          # For any initial/required rsync flags
          ARGS: "-avz --delete"
          # Source directory dist/ 需要到远端服务器的文件目录 **填入自己的打包路径**
          SOURCE: "dist/"
          # Remote host **填入自己的域名**
          REMOTE_HOST: "39.97.223.56"
          # Remote user **填入自己的用户,一般都是root用户**
          REMOTE_USER: "root"
          # Target directory 此处填写的是我博客域名下的action pacth下 **填入自己的域名路径**
          TARGET: "/web/engRoot"
